[build]
  command = "npm install --production=false && npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Force redirect rules
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset caching headers
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Security-Policy = "default-src 'self'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Specific image type headers
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/svg+xml" 