[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    cache-control = "public, immutable, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 